COMPONENT=AssociationExampleC

PFLAGS += 	-I../../ieee802154/includes \
			-I../../ieee802154/mac \
			-I../..//ieee802154/phy \
			-I../../ieee802154/timerasync \
			-I../../ieee802154/interfaces \
			-I../../ieee802154/interfaces/mac \
			-I../../ieee802154/interfaces/phy \
			-I../../cc2420 \
			-I.
include $(MAKERULES)

